# Generated by Django 4.1.3 on 2023-11-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_usertasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_nickname', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(default='', max_length=254)),
                ('user_password', models.IntegerField(default='')),
            ],
        ),
        migrations.RenameModel(
            old_name='UserTasks',
            new_name='UserComments',
        ),
    ]
