# Generated by Django 4.1.3 on 2023-11-24 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_users_rename_usertasks_usercomments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User2',
        ),
    ]
