# Generated by Django 4.1.3 on 2023-11-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_rename_users_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomments',
            name='airbnb_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usercomments',
            name='user_note',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user2',
            name='user_password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='usercomments',
            unique_together={('airbnb_name', 'user_nickname')},
        ),
        migrations.RemoveField(
            model_name='usercomments',
            name='user_task',
        ),
    ]
