# Generated by Django 4.1.3 on 2023-11-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_usercomments_airbnb_name_usercomments_user_note_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
