# Generated by Django 4.1.3 on 2023-11-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_delete_user2_remove_user_user_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomments',
            name='user_comment',
            field=models.CharField(default='', max_length=100),
        ),
    ]
