# Generated by Django 4.1.3 on 2023-11-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0007_usercomments_user_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='user_comment',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
