# Generated by Django 4.1.3 on 2023-11-24 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0008_alter_usercomments_user_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='user_nickname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.user'),
        ),
    ]
