# Generated by Django 4.1.3 on 2024-01-29 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0009_alter_usercomments_user_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('sinopse', models.TextField()),
                ('atores', models.ManyToManyField(to='api_rest.ator')),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.diretor')),
            ],
        ),
        migrations.DeleteModel(
            name='UserComments',
        ),
    ]
